name: offtk-examples
channels:
  - conda-forge
  - bioconda

# These dependencies are in addition to the toolkit itself
dependencies:
  - nglview
  - notebook
  - gromacs
  - qcelemental
  - qcportal >= 0.15
  - qcengine
  - openmmforcefields
  # Below are dependencies of the toolkit; they are listed here as a reference
  - mdtraj
  - numpy
  - openmm
  - openff-forcefields >= 2
  - openff-interchange < 0.2
  - gromacs
  - lammps
  - ambertools
  - ipywidgets =7
